/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SupplierRole;

import Business.Maintenance.MaintSchedule;
import Business.MedicalDevice.MedicalDevice;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Martin
 */
public class ManageMaintJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMaintJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ListSelectionModel cellSelectionModel;
    private myListSelectionListener listener;
    
    public ManageMaintJPanel(JPanel upc, UserAccount ua) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccount = ua;
        listener = new myListSelectionListener();
        
        poplateNewRequestTable();
//        maintenanceJTable.setCellSelectionEnabled(true);
        cellSelectionModel = maintenanceJTable.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        cellSelectionModel.addListSelectionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        maintenanceJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        problemJTxtArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        solutionJTxtArea = new javax.swing.JTextArea();
        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Maintenance Request Management");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        add(jLabel1, gridBagConstraints);

        maintenanceJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Device ID", "Name", "Model", "Service Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(maintenanceJTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 425;
        gridBagConstraints.ipady = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 39);
        add(jScrollPane1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Problem Descrption");
        jLabel2.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        add(jLabel2, gridBagConstraints);

        problemJTxtArea.setColumns(20);
        problemJTxtArea.setRows(5);
        problemJTxtArea.setEnabled(false);
        jScrollPane2.setViewportView(problemJTxtArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 425;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 39);
        add(jScrollPane2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Solution");
        jLabel3.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        add(jLabel3, gridBagConstraints);

        solutionJTxtArea.setColumns(20);
        solutionJTxtArea.setRows(5);
        solutionJTxtArea.setEnabled(false);
        jScrollPane3.setViewportView(solutionJTxtArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 425;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 39);
        add(jScrollPane3, gridBagConstraints);

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 12, 13, 0);
        add(backJButton, gridBagConstraints);

        submitJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submitJButton.setText("Served");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 3, 13, 39);
        add(submitJButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = maintenanceJTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "No request is selected!");
            return;
        }
        MedicalDevice md = (MedicalDevice)maintenanceJTable.getValueAt(selectedRow, 0);
        MaintSchedule ms = md.getMaintScheduleHistory().getLastMaintenace();
        ms.setLastMaintDate(new Date());
        ms.setNextMaintDate();
        if (ms.getmType().equals(MaintSchedule.MaintType.REP)) {
            ms.setFixDesp(solutionJTxtArea.getText());
        }
        md.setStatus("Operational");
        md.setLocation("Inventory");
        userAccount.getMaintRequestList().getMaintDevicesList().remove(md);
        poplateRequestTable();
    }//GEN-LAST:event_submitJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable maintenanceJTable;
    private javax.swing.JTextArea problemJTxtArea;
    private javax.swing.JTextArea solutionJTxtArea;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables

    private void poplateNewRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel)maintenanceJTable.getModel();
        dtm.setRowCount(0);
        
        for(MedicalDevice md : userAccount.getMaintRequestList().getMaintDevicesList()){
            Object[] row = new Object[4];
            row [0] = md;
            row [1] = md.getName();
            row [2] = md.getModel();
            row [3] = md.getMaintScheduleHistory().getLastMaintenace().getmType();
            
            dtm.addRow(row);
        }
    }
    
    private void poplateRequestTable() {
        cellSelectionModel.removeListSelectionListener(listener);
        DefaultTableModel dtm = (DefaultTableModel)maintenanceJTable.getModel();
        dtm.setRowCount(0);
        
        for(MedicalDevice md : userAccount.getMaintRequestList().getMaintDevicesList()){
            Object[] row = new Object[4];
            row [0] = md;
            row [1] = md.getName();
            row [2] = md.getModel();
            row [3] = md.getMaintScheduleHistory().getLastMaintenace().getmType();
            
            dtm.addRow(row);
        }
        cellSelectionModel.addListSelectionListener(listener);
    }
    
    class myListSelectionListener implements ListSelectionListener{
        public void valueChanged(ListSelectionEvent e) {
            int selectedRow = maintenanceJTable.getSelectedRow();
            MedicalDevice md = (MedicalDevice)maintenanceJTable.getValueAt(selectedRow, 0);
            if(md == null){
                JOptionPane.showMessageDialog(null, "No request is selected!");
                return;
            }
            if(md.getMaintScheduleHistory().getLastMaintenace().getmType().equals(MaintSchedule.MaintType.REP)){
                problemJTxtArea.setEnabled(true);
                problemJTxtArea.setText(md.getMaintScheduleHistory().getLastMaintenace().getProblemDesp());
                solutionJTxtArea.setEnabled(true);
            }
        }
    }
}
