/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.FinaceRole;

import Business.EcoSystem;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Martin
 */
public class AccountingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountingWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private EcoSystem system;
    private UserAccount userAccount;
    private Network network;
    
    public AccountingWorkAreaJPanel(JPanel upc, Organization org, EcoSystem ecosys, UserAccount ua, Network nw) {
        initComponents();
        this.userProcessContainer = upc;
        this.organization = org;
        this.system= ecosys;
        this.userAccount= ua;
        this.network = nw;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        paymentMgnJButton = new javax.swing.JButton();
        paymentViewJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Accounting Work Area");

        paymentMgnJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paymentMgnJButton.setText("Manage Payment >>");
        paymentMgnJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentMgnJButtonActionPerformed(evt);
            }
        });

        paymentViewJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paymentViewJButton.setText("View Payment History >>");
        paymentViewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentViewJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paymentMgnJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paymentViewJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(paymentMgnJButton)
                .addGap(45, 45, 45)
                .addComponent(paymentViewJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void paymentMgnJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentMgnJButtonActionPerformed
        // TODO add your handling code here:
        ManagePaymentJPanel jp = new ManagePaymentJPanel(userProcessContainer, organization, userAccount, network);
        userProcessContainer.add("ManageProductJPanel", jp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);       
    }//GEN-LAST:event_paymentMgnJButtonActionPerformed

    private void paymentViewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentViewJButtonActionPerformed
        // TODO add your handling code here:
        ViewPaymentHistoryJPanel jp = new ViewPaymentHistoryJPanel(userProcessContainer, organization, network);
        userProcessContainer.add("ViewPaymentHistoryJPanel", jp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);         
    }//GEN-LAST:event_paymentViewJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton paymentMgnJButton;
    private javax.swing.JButton paymentViewJButton;
    // End of variables declaration//GEN-END:variables
}
