/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.FinaceRole;

import Business.Bill.Bill;
import Business.EnterPrise.Enterprise;
import Business.Network.Network;
import Business.Order.Order;
import Business.Organization.FinanceOrganization;
import Business.Organization.Organization;
import Business.Payment.Payment;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Martin
 */
public class ManagePaymentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePaymentJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private Network network;
    private String paymentType;
    private UserAccount userAccount;
    
    public ManagePaymentJPanel(JPanel upc, Organization org, UserAccount ua, Network nw) {
        initComponents();
        this.userProcessContainer = upc;
        this.organization = org;
        this.userAccount = ua;
        this.network = nw;
        populateBillTable();
        
        buttonGroup.add(cashJRadioButton);
        buttonGroup.add(checkJRadioButton);
        buttonGroup.add(transferJRadioButton);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentJTable = new javax.swing.JTable();
        makePaymentJButton = new javax.swing.JButton();
        accountJLabel = new javax.swing.JLabel();
        cashJRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        checkJRadioButton = new javax.swing.JRadioButton();
        transferJRadioButton = new javax.swing.JRadioButton();
        viewOrderJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Manage Payment");

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        paymentJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Total", "Originator", "Supplier", "Account"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(paymentJTable);

        makePaymentJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        makePaymentJButton.setText("Payment");
        makePaymentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makePaymentJButtonActionPerformed(evt);
            }
        });

        accountJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accountJLabel.setText("Account");
        accountJLabel.setEnabled(false);

        cashJRadioButton.setText("Cash");
        cashJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashJRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Payment Type");

        txtAccount.setEditable(false);

        checkJRadioButton.setText("Check");
        checkJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkJRadioButtonActionPerformed(evt);
            }
        });

        transferJRadioButton.setText("Transfer");
        transferJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferJRadioButtonActionPerformed(evt);
            }
        });

        viewOrderJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewOrderJButton.setText("View Order Detail >>");
        viewOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cashJRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(checkJRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(transferJRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accountJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAccount))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(makePaymentJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(187, 187, 187)
                        .addComponent(viewOrderJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(viewOrderJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashJRadioButton)
                            .addComponent(checkJRadioButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(transferJRadioButton)
                                .addComponent(accountJLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(makePaymentJButton)
                            .addComponent(backJButton)))
                    .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkJRadioButtonActionPerformed
        // TODO add your handling code here:
        accountJLabel.setEnabled(false);
        txtAccount.setEditable(false);
        paymentType = "Check";
    }//GEN-LAST:event_checkJRadioButtonActionPerformed

    private void transferJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferJRadioButtonActionPerformed
        // TODO add your handling code here:
        accountJLabel.setEnabled(true);
        txtAccount.setEditable(true);
        paymentType = "Transfer";
    }//GEN-LAST:event_transferJRadioButtonActionPerformed

    private void viewOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = paymentJTable.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "No bill is selected");
            return;
        }        
        Bill bill = (Bill)paymentJTable.getValueAt(selectedRow, 0);
        Order order = bill.getOrder();
        ViewOrderDetailJPanel jp = new ViewOrderDetailJPanel(userProcessContainer,order);
        userProcessContainer.add("ViewOrderDetailJPanel", jp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
        
    }//GEN-LAST:event_viewOrderJButtonActionPerformed

    private void makePaymentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makePaymentJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = paymentJTable.getSelectedRow();
        int account;
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "No bill is selected");
            return;
        }   
        if((paymentType != null) && paymentType.equals("Transfer")){
            try{
                account = Integer.parseInt(txtAccount.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Bank account number can only be numbers.");
                return;
            }
        }else{
            account = 00000000;
        }
        Bill bill = (Bill)paymentJTable.getValueAt(selectedRow, 0);
        Payment payment = ((FinanceOrganization)organization).getPaymentDirectory().createPayment(bill);
        payment.setPaymentType(paymentType);
        payment.setPayBy(userAccount);
        payment.setPayTo(bill.getBillBy());
        payment.setAccount(account);
        populateBillTable();
    }//GEN-LAST:event_makePaymentJButtonActionPerformed

    private void cashJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashJRadioButtonActionPerformed
        // TODO add your handling code here:
        accountJLabel.setEnabled(false);
        txtAccount.setEditable(false);
        paymentType = "Cash";
    }//GEN-LAST:event_cashJRadioButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountJLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton cashJRadioButton;
    private javax.swing.JRadioButton checkJRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makePaymentJButton;
    private javax.swing.JTable paymentJTable;
    private javax.swing.JRadioButton transferJRadioButton;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JButton viewOrderJButton;
    // End of variables declaration//GEN-END:variables

    private void populateBillTable() {
        DefaultTableModel dtm = (DefaultTableModel)paymentJTable.getModel();
        dtm.setRowCount(0);
        boolean result = false;
        
        for(Bill bill : ((FinanceOrganization)organization).getBillDirectory().getBillList()){
            for(Payment pay : ((FinanceOrganization)organization).getPaymentDirectory().getPaymentList()){
                if(pay.getBill().equals(bill)){
                    result = true;
                    break;
                }else result = false;
            }
            if(!result){
                Object[] row = new Object[5];
                row[0] = bill;
                row[1] = bill.getAmount();
                row[2] = bill.getBillBy().getEmployee().getName();
                Enterprise ep = network.getEnterpriseDirectory().getEnterpriseByUserAccount(bill.getBillBy());
                row[3] = ep.toString();
                row[4] = bill.getAccountNumber();

                dtm.addRow(row);
            }
        }
    }
}
