/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AssetAdminRole;

import Business.Organization.AssetMgtOrganization;
import Business.Organization.Organization;
import Business.Surgery.SurgeryRequest;
import Business.SurgeryRoom.SurgeryRoom;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Martin
 */
public class ManageRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReservationMgnJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private String szDecision;
    
    public ManageRequestJPanel(JPanel upc, Organization org) {
        initComponents();
        this.userProcessContainer = upc;
        this.organization = org;
        buttonGroup.add(approveJRadioButton);
        buttonGroup.add(rejectJRadioButton);
        
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        decisioinJButton = new javax.swing.JButton();
        approveJRadioButton = new javax.swing.JRadioButton();
        rejectJRadioButton = new javax.swing.JRadioButton();

        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request Date", "Device ID", "Name", "Next Maint", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestJTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Manage Request");

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        decisioinJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        decisioinJButton.setText("Decision");
        decisioinJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decisioinJButtonActionPerformed(evt);
            }
        });

        approveJRadioButton.setText("Approve");
        approveJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJRadioButtonActionPerformed(evt);
            }
        });

        rejectJRadioButton.setText("Reject");
        rejectJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(312, 312, 312)
                                .addComponent(decisioinJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(approveJRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(rejectJRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(approveJRadioButton)
                    .addComponent(rejectJRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(decisioinJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void decisioinJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decisioinJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = requestJTable.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "No request is selected");
            return;
        }
        
        SurgeryRequest request = (SurgeryRequest)requestJTable.getValueAt(selectedRow, 0);
        Date nextMaintDate = request.getSurgerySchedule().getMedicalDevice().getMaintScheduleHistory().getLastMaintenace().getNextMaintDate();        
        request.setStatus(szDecision);
        if(request.getSurgerySchedule().getDate().after(nextMaintDate)){
            JOptionPane.showMessageDialog(null, "Request date is after equipment next maintenance date! You can't approve this request!");
             request.setStatus("Rejected");
        }

        if(szDecision.equals("Approved")){
            SurgeryRoom room = request.getSurgeryRoom();
            room.getSgyScheduleDirectory().getSurgeryScheduleList().add(request.getSurgerySchedule());
        }
    }//GEN-LAST:event_decisioinJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void approveJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJRadioButtonActionPerformed
        // TODO add your handling code here:
        szDecision = "Approved";
    }//GEN-LAST:event_approveJRadioButtonActionPerformed

    private void rejectJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJRadioButtonActionPerformed
        // TODO add your handling code here:
        szDecision = "Rejected";
    }//GEN-LAST:event_rejectJRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton approveJRadioButton;
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton decisioinJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rejectJRadioButton;
    private javax.swing.JTable requestJTable;
    // End of variables declaration//GEN-END:variables

    private void populateRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel)requestJTable.getModel();
        dtm.setRowCount(0);
        SimpleDateFormat dateformat = new SimpleDateFormat("dd/MM/yyyy");
        
        for(SurgeryRequest request : ((AssetMgtOrganization)organization).getSurgeryRequestList()){
            Object[] row = new Object[5];
            
            row[0] = request;
            row[1] = request.getSurgerySchedule().getMedicalDevice().getDeviceID();
            row[2] = request.getSurgerySchedule().getMedicalDevice().getName();
            row[3] = dateformat.format(request.getSurgerySchedule().getMedicalDevice().getMaintScheduleHistory().getLastMaintenace().getNextMaintDate());
            row[4] = request.getStatus();
            
            dtm.addRow(row);
        }
    }
}
